"""Initial revision

Revision ID: d703b66263b6
Revises: 
Create Date: 2026-07-19 19:29:16.455076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd703b66263b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('deposit', 'withdraw', name='operation'), nullable=True),
    sa.Column('amount', sa.Double(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('wallet_uuid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_uuid'], ['wallets.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('wallets')
    # ### end Alembic commands ###
